-- Generated from /Users/kinjiru/Downloads/Untitled spreadsheet - Sheet1.csv
-- Generated on 2026-06-14.
-- Creates the system deck "5,000 Chinese Conversation Sentences" and imports 430 CSV rows.
-- Safe to rerun: existing deck, topics, sentences, and deck-item links are reused when they match this import.

begin;

create temporary table chinese_conversation_sentence_payload (
  csv_position integer not null,
  chinese text not null,
  pinyin text,
  english text not null,
  item_order integer not null,
  type_code text,
  topic text not null
) on commit drop;

insert into chinese_conversation_sentence_payload (csv_position, chinese, pinyin, english, item_order, type_code, topic)
values
  (1, '我叫...', 'Wǒ jiào..', 'My name is...', 1, 'cc_1', 'Name'),
  (2, '我姓...', 'Wǒ xìng...', 'My last name is...', 2, 'cc_1', 'Name'),
  (3, '你叫我Jane就好。', 'Nǐ jiào wǒ Jane jiù hǎo.', 'Just call me Jane', 3, 'cc_1', 'Name'),
  (4, '家人都叫我 "Jenny"。', 'Jiārén dōu jiào wǒ "Jenny".', 'My family calls me "Jenny"', 4, 'cc_1', 'Name'),
  (5, '朋友都叫我 "Jen"。', 'Péngyǒu dōu jiào wǒ "Jen".', 'My friends call me "Jen."', 5, 'cc_1', 'Name'),
  (6, '我沒有英文名字。', 'Wǒ méiyǒu Yīngwén míngzi.', 'I don''t have an English name.', 6, 'cc_1', 'Name'),
  (7, '我的英文名字是老師幫我取的。', 'Wǒ de Yīngwén míngzi shì lǎoshī bāng wǒ qǔ de.', 'My teacher gave me my English name.', 7, 'cc_1', 'Name'),
  (8, '同事都叫我英文名字 "Jane".', 'Tóngshì dōu jiào wǒ Yīngwén míngzi — Jane.', 'My coworkers usually call me by my English name, Jane.', 8, 'cc_1', 'Name'),
  (9, '我不喜歡我的綽號。', 'Wǒ bù xǐhuān wǒ de chuòhào.', 'I don''t like my nickname.', 9, 'cc_1', 'Name'),
  (10, '大家常常把我的名字念錯。', 'Dàjiā chángcháng bǎ wǒ de míngzi niàn cuò.', 'People often mispronounce my name.', 10, 'cc_1', 'Name'),
  (11, '我有一個朋友跟我同名。', 'Wǒ yǒu yí ge péngyǒu gēn wǒ tóngmíng.', 'One of my friends has the same name as me.', 11, 'cc_1', 'Name'),
  (12, '我的名字是我爸取的。', 'Wǒ de míngzi shì wǒ bà qǔ de.', 'My dad gave me my name.', 12, 'cc_1', 'Name'),
  (13, '我的名字是算命師取的。', 'Wǒ de míngzi shì suànmìngshī qǔ de.', 'My name was chosen by a fortune teller.', 13, 'cc_1', 'Name'),
  (14, '我的名字代表「勇敢」。', 'Wǒ de míngzi dàibiǎo "yǒnggǎn".', 'My name means "brave."', 14, 'cc_1', 'Name'),
  (15, '我的名字很常見。', 'Wǒ de míngzi hěn chángjiàn.', 'My name is quite common.', 15, 'cc_1', 'Name'),
  (16, '我很想改名字。', 'Wǒ hěn xiǎng gǎi míngzi.', 'I''d really like to change my name.', 16, 'cc_1', 'Name'),
  (17, '我很喜歡我的名字。', 'Wǒ hěn xǐhuān wǒ de míngzi.', 'I really like my name.', 17, 'cc_1', 'Name'),
  (18, '我今年二十五。', 'Wǒ jīnnián èrshíwǔ.', 'I''m twenty-five this year.', 1, 'cc_2', 'Age'),
  (19, '我還不到十八歲。', 'Wǒ hái bú dào shíbā suì.', 'I''m not eighteen yet.', 2, 'cc_2', 'Age'),
  (20, '我快五十了。', 'Wǒ kuài wǔshí le.', 'I''m almost fifty.', 3, 'cc_2', 'Age'),
  (21, '我三十幾了。', 'Wǒ sānshí jǐ le.', 'I''m in my thirties.', 4, 'cc_2', 'Age'),
  (22, '我剛滿四十歲。', 'Wǒ gāng mǎn sìshí suì.', 'I just turned forty.', 5, 'cc_2', 'Age'),
  (23, '我屬羊。', 'Wǒ shǔ yáng.', 'I''m a Goat.', 6, 'cc_2', 'Age'),
  (24, '我跟你同年。', 'Wǒ gēn nǐ tóngnián.', 'We were born in the same year.', 7, 'cc_2', 'Age'),
  (25, '我是一九八○年生的。', 'Wǒ shì yījiǔbālíng nián shēng de.', 'I was born in 1980.', 8, 'cc_2', 'Age'),
  (26, '我同事都比我小。', 'Wǒ tóngshì dōu bǐ wǒ xiǎo.', 'All my coworkers are younger than me.', 9, 'cc_2', 'Age'),
  (27, '我跟我妹差十歲。', 'Wǒ gēn wǒ mèi chà shí suì.', 'My sister and I are ten years apart.', 10, 'cc_2', 'Age'),
  (28, '我比我哥小三歲。', 'Wǒ bǐ wǒ gē xiǎo sān suì.', 'I''m three years younger than my brother.', 11, 'cc_2', 'Age'),
  (29, '我早就過適婚年齡了。', 'Wǒ zǎo jiù guò shìhūn niánlíng le.', 'I''m long past the marriageable age.', 12, 'cc_2', 'Age'),
  (30, '我不年輕了。', 'Wǒ bù niánqīng le.', 'I''m not young anymore.', 13, 'cc_2', 'Age'),
  (31, '我看起來比實際年齡年輕。', 'Wǒ kàn qǐlái bǐ shíjì niánlíng niánqīng.', 'I look younger than my actual age.', 14, 'cc_2', 'Age'),
  (32, '女人的年齡是祕密。', 'Nǚrén de niánlíng shì mìmì.', 'A woman''s age is a secret.', 15, 'cc_2', 'Age'),
  (33, '我不喜歡人家問我年齡。', 'Wǒ bù xǐhuān rénjiā wèn wǒ niánlíng.', 'I don''t like people asking my age.', 16, 'cc_2', 'Age'),
  (34, '我是台灣人。', 'Wǒ shì Táiwān rén.', 'I''m Taiwanese.', 1, 'cc_3', 'Hometown'),
  (35, '我是高雄人。', 'Wǒ shì Gāoxióng rén.', 'I''m from Kaohsiung.', 2, 'cc_3', 'Hometown'),
  (36, '我來自台灣中部。', 'Wǒ láizì Táiwān zhōngbù.', 'I''m from central Taiwan.', 3, 'cc_3', 'Hometown'),
  (37, '我是在台灣東部出生的。', 'Wǒ shì zài Táiwān dōngbù chūshēng de.', 'I was born in eastern Taiwan.', 4, 'cc_3', 'Hometown'),
  (38, '我很愛我的家鄉。', 'Wǒ hěn ài wǒ de jiāxiāng.', 'I really love my hometown.', 5, 'cc_3', 'Hometown'),
  (39, '我從小在家鄉長大。', 'Wǒ cóngxiǎo zài jiāxiāng zhǎngdà.', 'I grew up in my hometown.', 6, 'cc_3', 'Hometown'),
  (40, '我十歲的時候離開家鄉。', 'Wǒ shí suì de shíhou líkāi jiāxiāng.', 'I left my hometown when I was ten.', 7, 'cc_3', 'Hometown'),
  (41, '我從小就在外地生活。', 'Wǒ cóngxiǎo jiù zài wàidì shēnghuó.', 'I''ve lived away from my hometown since I was young.', 8, 'cc_3', 'Hometown'),
  (42, '我對家鄉的印象不深。', 'Wǒ duì jiāxiāng de yìnxiàng bù shēn.', 'I don''t remember much about my hometown.', 9, 'cc_3', 'Hometown'),
  (43, '我常回家鄉看爸媽。', 'Wǒ cháng huí jiāxiāng kàn bàmā.', 'I often go back to my hometown to see my parents.', 10, 'cc_3', 'Hometown'),
  (44, '我的家鄉是個很熱鬧的大城市。', 'Wǒ de jiāxiāng shì ge hěn rènào de dà chéngshì.', 'My hometown is a big, lively city.', 11, 'cc_3', 'Hometown'),
  (45, '我的家鄉盛產稻米。', 'Wǒ de jiāxiāng shèngchǎn dàomǐ.', 'My hometown is known for its rice production.', 12, 'cc_3', 'Hometown'),
  (46, '家鄉永遠是我最懷念的地方。', 'Jiāxiāng yǒngyuǎn shì wǒ zuì huáiniàn de dìfang.', 'My hometown will always be the place I miss the most.', 13, 'cc_3', 'Hometown'),
  (47, '我的家鄉非常漂亮。', 'Wǒ de jiāxiāng fēicháng piàoliang.', 'My hometown is very beautiful.', 14, 'cc_3', 'Hometown'),
  (48, '我住在台北市。', 'Wǒ zhù zài Táiběi Shì.', 'I live in Taipei City.', 1, 'cc_4', 'Family'),
  (49, '我們家有四個人。', 'Wǒmen jiā yǒu sì ge rén.', 'There are four people in my family.', 2, 'cc_4', 'Family'),
  (50, '我是在單親家庭長大的。', 'Wǒ shì zài dānqīn jiātíng zhǎngdà de.', 'I grew up in a single-parent family.', 3, 'cc_4', 'Family'),
  (51, '我是獨生子。', 'Wǒ shì dúshēngzǐ.', 'I''m an only child.', 4, 'cc_4', 'Family'),
  (52, '我們家感情很好。', 'Wǒmen jiā gǎnqíng hěn hǎo.', 'My family is very close.', 5, 'cc_4', 'Family'),
  (53, '我是家裡最大的。', 'Wǒ shì jiālǐ zuì dà de.', 'I''m the oldest child in my family.', 6, 'cc_4', 'Family'),
  (54, '我住公寓。', 'Wǒ zhù gōngyù.', 'I live in an apartment.', 7, 'cc_4', 'Family'),
  (55, '我們家三代同堂。', 'Wǒmen jiā sāndài tóngtáng.', 'Three generations of my family live together.', 8, 'cc_4', 'Family'),
  (56, '我貸款買房子。', 'Wǒ dàikuǎn mǎi fángzi.', 'I bought a house with a mortgage.', 9, 'cc_4', 'Family'),
  (57, '我跟爸媽一起住。', 'Wǒ gēn bàmā yìqǐ zhù.', 'I live with my parents.', 10, 'cc_4', 'Family'),
  (58, '我跟妹妹住同一個房間。', 'Wǒ gēn mèimei zhù tóng yí ge fángjiān.', 'I share a room with my younger sister.', 11, 'cc_4', 'Family'),
  (59, '我一個人租房子住。', 'Wǒ yí ge rén zū fángzi zhù.', 'I rent a place and live by myself.', 12, 'cc_4', 'Family'),
  (60, '我們家是雙薪家庭。', 'Wǒmen jiā shì shuāngxīn jiātíng.', 'We are a dual-income family.', 13, 'cc_4', 'Family'),
  (61, '我三年前搬來這裡。', 'Wǒ sān nián qián bān lái zhèlǐ.', 'I moved here three years ago.', 14, 'cc_4', 'Family'),
  (62, '我家樓下就有7-11。', 'Wǒ jiā lóuxià jiù yǒu Seven-Eleven.', 'There''s a 7-Eleven right downstairs from my place.', 15, 'cc_4', 'Family'),
  (63, '我家離捷運站很近。', 'Wǒ jiā lí Jiéyùn Zhàn hěn jìn.', 'My place is very close to the MRT station.', 16, 'cc_4', 'Family'),
  (64, '我住在郊區。', 'Wǒ zhù zài jiāoqū.', 'I live in the suburbs.', 17, 'cc_4', 'Family'),
  (65, '我個性很外向。', 'Wǒ gèxìng hěn wàixiàng.', 'I''m very outgoing.', 1, 'cc_5', 'Personality'),
  (66, '我比較內向。', 'Wǒ bǐjiào nèixiàng.', 'I''m more introverted.', 2, 'cc_5', 'Personality'),
  (67, '我話不多。', 'Wǒ huà bù duō.', 'I''m not very talkative.', 3, 'cc_5', 'Personality'),
  (68, '我很喜歡交朋友。', 'Wǒ hěn xǐhuān jiāo péngyǒu.', 'I really enjoy making friends.', 4, 'cc_5', 'Personality'),
  (69, '我很有正義感。', 'Wǒ hěn yǒu zhèngyìgǎn.', 'I have a strong sense of justice.', 5, 'cc_5', 'Personality'),
  (70, '我喜歡接受挑戰。', 'Wǒ xǐhuān jiēshòu tiǎozhàn.', 'I like taking on challenges.', 6, 'cc_5', 'Personality'),
  (71, '我很喜歡幫助別人。', 'Wǒ hěn xǐhuān bāngzhù biérén.', 'I like helping others.', 7, 'cc_5', 'Personality'),
  (72, '我天生很樂觀。', 'Wǒ tiānshēng hěn lèguān.', 'I''m naturally optimistic.', 8, 'cc_5', 'Personality'),
  (73, '我個性很隨和。', 'Wǒ gèxìng hěn suíhé.', 'I''m easygoing.', 9, 'cc_5', 'Personality'),
  (74, '我脾氣很好。', 'Wǒ píqi hěn hǎo.', 'I have a good temper.', 10, 'cc_5', 'Personality'),
  (75, '我很怕孤單。', 'Wǒ hěn pà gūdān.', 'I don''t like being alone.', 11, 'cc_5', 'Personality'),
  (76, '我很愛開玩笑。', 'Wǒ hěn ài kāi wánxiào.', 'I like joking around.', 12, 'cc_5', 'Personality'),
  (77, '我很容易緊張。', 'Wǒ hěn róngyì jǐnzhāng.', 'I get nervous easily.', 13, 'cc_5', 'Personality'),
  (78, '我有點固執。', 'Wǒ yǒudiǎn gùzhí.', 'I''m a little stubborn.', 14, 'cc_5', 'Personality'),
  (79, '我是急性子。', 'Wǒ shì jíxìngzi.', 'I''m impatient.', 15, 'cc_5', 'Personality'),
  (80, '我很喜歡聽音樂。', 'Wǒ hěn xǐhuān tīng yīnyuè.', 'I really like listening to music.', 1, 'cc_6', 'Hobbies'),
  (81, '我很喜歡逛展覽。', 'Wǒ hěn xǐhuān guàng zhǎnlǎn.', 'I enjoy going to exhibitions.', 2, 'cc_6', 'Hobbies'),
  (82, '我很喜歡出國玩。', 'Wǒ hěn xǐhuān chūguó wán.', 'I really like traveling abroad.', 3, 'cc_6', 'Hobbies'),
  (83, '我每天都會去散步。', 'Wǒ měitiān dōu huì qù sànbù.', 'I go for a walk every day.', 4, 'cc_6', 'Hobbies'),
  (84, '我放假的時候喜歡出去走走。', 'Wǒ fàngjià de shíhou xǐhuān chūqù zǒuzou.', 'I like going out during my time off.', 5, 'cc_6', 'Hobbies'),
  (85, '我習慣睡前看點書。', 'Wǒ xíguàn shuì qián kàn diǎn shū.', 'I usually read a little before bed.', 6, 'cc_6', 'Hobbies'),
  (86, '我常跟朋友去看電影。', 'Wǒ cháng gēn péngyǒu qù kàn diànyǐng.', 'I often go to the movies with my friends.', 7, 'cc_6', 'Hobbies'),
  (87, '我常跟家人去爬山。', 'Wǒ cháng gēn jiārén qù páshān.', 'I often go hiking with my family.', 8, 'cc_6', 'Hobbies'),
  (88, '我超愛講電話。', 'Wǒ chāo ài jiǎng diànhuà.', 'I love talking on the phone.', 9, 'cc_6', 'Hobbies'),
  (89, '我很喜歡跟人聊天。', 'Wǒ hěn xǐhuān gēn rén liáotiān.', 'I like chatting with people.', 10, 'cc_6', 'Hobbies'),
  (90, '我最近迷上網路遊戲了。', 'Wǒ zuìjìn mí shàng wǎnglù yóuxì le.', 'I''ve gotten really into online games lately.', 11, 'cc_6', 'Hobbies'),
  (91, '我很喜歡吃美食。', 'Wǒ hěn xǐhuān chī měishí.', 'I love trying good food.', 12, 'cc_6', 'Hobbies'),
  (92, '我最喜歡的休閒活動是釣魚。', 'Wǒ zuì xǐhuān de xiūxián huódòng shì diàoyú.', 'My favorite hobby is fishing.', 13, 'cc_6', 'Hobbies'),
  (93, '我會說四種語言。', 'Wǒ huì shuō sì zhǒng yǔyán.', 'I can speak four languages.', 1, 'cc_7', 'Skills'),
  (94, '我的英文很好。', 'Wǒ de Yīngwén hěn hǎo.', 'My English is very good.', 2, 'cc_7', 'Skills'),
  (95, '我很會跳舞。', 'Wǒ hěn huì tiàowǔ.', 'I''m a good dancer.', 3, 'cc_7', 'Skills'),
  (96, '我什麼運動都會。', 'Wǒ shénme yùndòng dōu huì.', 'I''m good at all kinds of sports.', 4, 'cc_7', 'Skills'),
  (97, '我跑得很快。', 'Wǒ pǎo de hěn kuài.', 'I can run very fast.', 5, 'cc_7', 'Skills'),
  (98, '我很會彈鋼琴。', 'Wǒ hěn huì tán gāngqín.', 'I''m good at playing the piano.', 6, 'cc_7', 'Skills'),
  (99, '我有救生員執照。', 'Wǒ yǒu jiùshēngyuán zhízhào.', 'I have a lifeguard license.', 7, 'cc_7', 'Skills'),
  (100, '我很會用電腦。', 'Wǒ hěn huì yòng diànnǎo.', 'I''m good with computers.', 8, 'cc_7', 'Skills'),
  (101, '我會游自由式。', 'Wǒ huì yóu zìyóushì.', 'I can swim freestyle.', 9, 'cc_7', 'Skills'),
  (102, '我很會做菜。', 'Wǒ hěn huì zuò cài.', 'I''m a good cook.', 10, 'cc_7', 'Skills'),
  (103, '大家都說我唱歌很好聽。', 'Dàjiā dōu shuō wǒ chànggē hěn hǎotīng.', 'Everyone says I sing well.', 11, 'cc_7', 'Skills'),
  (104, '我很會做甜點。', 'Wǒ hěn huì zuò tiándiǎn.', 'I''m good at making desserts.', 12, 'cc_7', 'Skills'),
  (105, '我會開車。', 'Wǒ huì kāichē.', 'I can drive.', 13, 'cc_7', 'Skills'),
  (106, '我是空手道黑帶。', 'Wǒ shì kōngshǒudào hēidài.', 'I have a black belt in karate.', 14, 'cc_7', 'Skills'),
  (107, '我很會畫畫。', 'Wǒ hěn huì huàhuà.', 'I''m good at painting.', 15, 'cc_7', 'Skills'),
  (108, '我會自己做衣服。', 'Wǒ huì zìjǐ zuò yīfu.', 'I can make my own clothes.', 16, 'cc_7', 'Skills'),
  (109, '同事都覺得我是開心果。', 'Tóngshì dōu juéde wǒ shì kāixīnguǒ.', 'My coworkers all think I''m the funny one.', 1, 'cc_8', 'How Others See Me'),
  (110, '朋友很喜歡找我聊天。', 'Péngyǒu hěn xǐhuān zhǎo wǒ liáotiān.', 'My friends like talking to me about their problems.', 2, 'cc_8', 'How Others See Me'),
  (111, '老闆都誇我很有衝勁。', 'Lǎobǎn dōu kuā wǒ hěn yǒu chōngjìn.', 'My boss says I''m very energetic.', 3, 'cc_8', 'How Others See Me'),
  (112, '主管說我做事很細心。', 'Zhǔguǎn shuō wǒ zuòshì hěn xìxīn.', 'My manager says I''m very detail-oriented.', 4, 'cc_8', 'How Others See Me'),
  (113, '我爸媽覺得我有點孩子氣。', 'Wǒ bàmā juéde wǒ yǒudiǎn háiziqì.', 'My parents think I''m a bit childish.', 5, 'cc_8', 'How Others See Me'),
  (114, '老闆說我工作很認真。', 'Lǎobǎn shuō wǒ gōngzuò hěn rènzhēn.', 'My boss says I take my work seriously.', 6, 'cc_8', 'How Others See Me'),
  (115, '我男朋友覺得我太依賴他了。', 'Wǒ nánpéngyǒu juéde wǒ tài yīlài tā le.', 'My boyfriend thinks I depend on him too much.', 7, 'cc_8', 'How Others See Me'),
  (116, '長輩都誇我很聰明。', 'Zhǎngbèi dōu kuā wǒ hěn cōngmíng.', 'Older people often praise me for being smart.', 8, 'cc_8', 'How Others See Me'),
  (117, '大家都說我很有耐心。', 'Dàjiā dōu shuō wǒ hěn yǒu nàixīn.', 'Everyone says I''m very patient.', 9, 'cc_8', 'How Others See Me'),
  (118, '有人說我是溫室裡的花朵。', 'Yǒurén shuō wǒ shì wēnshì lǐ de huāduǒ.', 'Some people say I''ve been sheltered.', 10, 'cc_8', 'How Others See Me'),
  (119, '有人覺得我太嚴肅了。', 'Yǒurén juéde wǒ tài yánsù le.', 'Some people think I''m too serious.', 11, 'cc_8', 'How Others See Me'),
  (120, '朋友叫我不要想太多。', 'Péngyǒu jiào wǒ búyào xiǎng tài duō.', 'My friends tell me not to overthink things.', 12, 'cc_8', 'How Others See Me'),
  (121, '大家都說我是個迷糊蛋。', 'Dàjiā dōu shuō wǒ shì ge míhúdàn.', 'Everyone says I''m absent-minded.', 13, 'cc_8', 'How Others See Me'),
  (122, '大家都說我脾氣很好。', 'Dàjiā dōu shuō wǒ píqi hěn hǎo.', 'Everyone says I have a good temper.', 14, 'cc_8', 'How Others See Me'),
  (123, '我現在單身。', 'Wǒ xiànzài dānshēn.', 'I''m single.', 1, 'cc_9', 'Marital Status'),
  (124, '我完全不想結婚。', 'Wǒ wánquán bù xiǎng jiéhūn.', 'I have no interest in getting married.', 2, 'cc_9', 'Marital Status'),
  (125, '我兩年前結婚了。', 'Wǒ liǎng nián qián jiéhūn le.', 'I got married two years ago.', 3, 'cc_9', 'Marital Status'),
  (126, '我上個月訂婚了。', 'Wǒ shàng ge yuè dìnghūn le.', 'I got engaged last month.', 4, 'cc_9', 'Marital Status'),
  (127, '我今年年底要結婚。', 'Wǒ jīnnián niándǐ yào jiéhūn.', 'I''m getting married at the end of this year.', 5, 'cc_9', 'Marital Status'),
  (128, '我結婚十年了。', 'Wǒ jiéhūn shí nián le.', 'I''ve been married for ten years.', 6, 'cc_9', 'Marital Status'),
  (129, '我的婚姻很幸福。', 'Wǒ de hūnyīn hěn xìngfú.', 'I have a happy marriage.', 7, 'cc_9', 'Marital Status'),
  (130, '我是家庭主婦。', 'Wǒ shì jiātíng zhǔfù.', 'I''m a homemaker.', 8, 'cc_9', 'Marital Status'),
  (131, '我跟我先生以前是同學。', 'Wǒ gēn wǒ xiānsheng yǐqián shì tóngxué.', 'My husband and I were classmates.', 9, 'cc_9', 'Marital Status'),
  (132, '我是因為懷孕才結婚的。', 'Wǒ shì yīnwèi huáiyùn cái jiéhūn de.', 'I got married because I was pregnant.', 10, 'cc_9', 'Marital Status'),
  (133, '我結婚不到半年就懷孕了。', 'Wǒ jiéhūn bú dào bàn nián jiù huáiyùn le.', 'I got pregnant less than six months after getting married.', 11, 'cc_9', 'Marital Status'),
  (134, '這是我的第二次婚姻。', 'Zhè shì wǒ de dì èr cì hūnyīn.', 'This is my second marriage.', 12, 'cc_9', 'Marital Status'),
  (135, '我離婚好幾年了。', 'Wǒ líhūn hǎo jǐ nián le.', 'I''ve been divorced for several years.', 13, 'cc_9', 'Marital Status'),
  (136, '我跟婆婆處得不太好。', 'Wǒ gēn pópo chǔ de bú tài hǎo.', 'I don''t get along very well with my mother-in-law.', 14, 'cc_9', 'Marital Status'),
  (137, '我有點後悔結婚。', 'Wǒ yǒudiǎn hòuhuǐ jiéhūn.', 'I sometimes regret getting married.', 15, 'cc_9', 'Marital Status'),
  (138, '我身高一百六十公分。', 'Wǒ shēngāo yì bǎi liùshí gōngfēn.', 'I''m 160 centimeters tall.', 1, 'cc_10', 'Height'),
  (139, '我很久沒量身高了。', 'Wǒ hěn jiǔ méi liáng shēngāo le.', 'I haven''t measured my height in a long time.', 2, 'cc_10', 'Height'),
  (140, '我對自己的身高很滿意。', 'Wǒ duì zìjǐ de shēngāo hěn mǎnyì.', 'I''m happy with my height.', 3, 'cc_10', 'Height'),
  (141, '我的身高算中等。', 'Wǒ de shēngāo suàn zhōngděng.', 'I''m of average height.', 4, 'cc_10', 'Height'),
  (142, '我的身高像我爸。', 'Wǒ de shēngāo xiàng wǒ bà.', 'I got my height from my dad.', 5, 'cc_10', 'Height'),
  (143, '我跟你一樣高。', 'Wǒ gēn nǐ yíyàng gāo.', 'I''m the same height as you.', 6, 'cc_10', 'Height'),
  (144, '我比我姊矮三公分。', 'Wǒ bǐ wǒ jiě ǎi sān gōngfēn.', 'I''m three centimeters shorter than my older sister.', 7, 'cc_10', 'Height'),
  (145, '我比我弟高五公分。', 'Wǒ bǐ wǒ dì gāo wǔ gōngfēn.', 'I''m five centimeters taller than my younger brother.', 8, 'cc_10', 'Height'),
  (146, '我個子不高。', 'Wǒ gèzi bù gāo.', 'I''m not very tall.', 9, 'cc_10', 'Height'),
  (147, '我很羨慕高個子的人。', 'Wǒ hěn xiànmù gāo gèzi de rén.', 'I envy people who are tall.', 10, 'cc_10', 'Height'),
  (148, '我是家裡最高的。', 'Wǒ shì jiālǐ zuì gāo de.', 'I''m the tallest person in my family.', 11, 'cc_10', 'Height'),
  (149, '我只有一百四十五公分。', 'Wǒ zhǐyǒu yì bǎi sìshíwǔ gōngfēn.', 'I''m only 145 centimeters tall.', 12, 'cc_10', 'Height'),
  (150, '我身高超過一百九十公分。', 'Wǒ shēngāo chāoguò yì bǎi jiǔshí gōngfēn.', 'I''m over 190 centimeters tall.', 13, 'cc_10', 'Height'),
  (151, '我上國中以後才開始長高。', 'Wǒ shàng guózhōng yǐhòu cái kāishǐ zhǎnggāo.', 'I didn''t start getting taller until junior high school.', 14, 'cc_10', 'Height'),
  (152, '我體重四十八公斤。', 'Wǒ tǐzhòng sìshíbā gōngjīn.', 'I weigh 48 kilograms.', 1, 'cc_11', 'Body Type'),
  (153, '我不到六十公斤。', 'Wǒ bú dào liùshí gōngjīn.', 'I weigh less than 60 kilograms.', 2, 'cc_11', 'Body Type'),
  (154, '我有點胖。', 'Wǒ yǒudiǎn pàng.', 'I''m a little overweight.', 3, 'cc_11', 'Body Type'),
  (155, '我很瘦。', 'Wǒ hěn shòu.', 'I''m very slim.', 4, 'cc_11', 'Body Type'),
  (156, '我很羨慕怎麼吃都不會胖的人。', 'Wǒ hěn xiànmù zěnme chī dōu bú huì pàng de rén.', 'I envy people who never seem to gain weight no matter how much they eat.', 5, 'cc_11', 'Body Type'),
  (157, '我的身材算中等。', 'Wǒ de shēncái suàn zhōngděng.', 'I have an average build.', 6, 'cc_11', 'Body Type'),
  (158, '我比我哥重十公斤。', 'Wǒ bǐ wǒ gē zhòng shí gōngjīn.', 'I weigh 10 kilograms more than my older brother.', 7, 'cc_11', 'Body Type'),
  (159, '我比我妹瘦。', 'Wǒ bǐ wǒ mèi shòu.', 'I''m thinner than my younger sister.', 8, 'cc_11', 'Body Type'),
  (160, '我的胸圍是三十四吋。', 'Wǒ de xiōngwéi shì sānshísì cùn.', 'My bust measurement is 34 inches.', 9, 'cc_11', 'Body Type'),
  (161, '我的手臂肉肉的。', 'Wǒ de shǒubì ròuròu de.', 'My arms are a bit chubby.', 10, 'cc_11', 'Body Type'),
  (162, '我的大腿有點粗。', 'Wǒ de dàtuǐ yǒudiǎn cū.', 'My thighs are a little thick.', 11, 'cc_11', 'Body Type'),
  (163, '我靠運動維持身材。', 'Wǒ kào yùndòng wéichí shēncái.', 'I stay in shape through exercise.', 12, 'cc_11', 'Body Type'),
  (164, '我覺得自己有點胖。', 'Wǒ juéde zìjǐ yǒudiǎn pàng.', 'I think I''m a little overweight.', 13, 'cc_11', 'Body Type'),
  (165, '我覺得自己太瘦了。', 'Wǒ juéde zìjǐ tài shòu le.', 'I think I''m too skinny.', 14, 'cc_11', 'Body Type'),
  (166, '我最近胖了一點。', 'Wǒ zuìjìn pàng le yìdiǎn.', 'I''ve gained a little weight recently.', 15, 'cc_11', 'Body Type'),
  (167, '我變白了。', 'Wǒ biàn bái le.', 'I''ve gotten lighter-skinned.', 1, 'cc_12', 'Skin'),
  (168, '我的皮膚很白。', 'Wǒ de pífū hěn bái.', 'I have fair skin.', 2, 'cc_12', 'Skin'),
  (169, '我很容易曬黑。', 'Wǒ hěn róngyì shàihēi.', 'I tan easily.', 3, 'cc_12', 'Skin'),
  (170, '我曬黑了。', 'Wǒ shàihēi le.', 'I''ve gotten a tan.', 4, 'cc_12', 'Skin'),
  (171, '我的膚質很好。', 'Wǒ de fūzhí hěn hǎo.', 'I have really nice skin.', 5, 'cc_12', 'Skin'),
  (172, '我的臉色有點蒼白。', 'Wǒ de liǎnsè yǒudiǎn cāngbái.', 'My face looks a little pale.', 6, 'cc_12', 'Skin'),
  (173, '我的皮膚不太吃妝。', 'Wǒ de pífū bú tài chīzhuāng.', 'Makeup doesn''t stay on my skin very well.', 7, 'cc_12', 'Skin'),
  (174, '我是油性肌膚。', 'Wǒ shì yóuxìng jīfū.', 'I have oily skin.', 8, 'cc_12', 'Skin'),
  (175, '我的皮膚很光滑。', 'Wǒ de pífū hěn guānghuá.', 'My skin is very smooth.', 9, 'cc_12', 'Skin'),
  (176, '我是混合性肌膚。', 'Wǒ shì hùnhéxìng jīfū.', 'I have combination skin.', 10, 'cc_12', 'Skin'),
  (177, '我的皮膚很容易過敏。', 'Wǒ de pífū hěn róngyì guòmǐn.', 'My skin is easily irritated.', 11, 'cc_12', 'Skin'),
  (178, '我有黑眼圈。', 'Wǒ yǒu hēiyǎnquān.', 'I have dark circles under my eyes.', 12, 'cc_12', 'Skin'),
  (179, '我的皮膚很有光澤。', 'Wǒ de pífū hěn yǒu guāngzé.', 'My skin has a healthy glow.', 13, 'cc_12', 'Skin'),
  (180, '我很容易長痘痘。', 'Wǒ hěn róngyì zhǎng dòudou.', 'I break out easily.', 14, 'cc_12', 'Skin'),
  (181, '我只要熬夜，臉色就會變差。', 'Wǒ zhǐyào áoyè, liǎnsè jiù huì biàn chà.', 'If I stay up late, my complexion gets worse.', 15, 'cc_12', 'Skin'),
  (182, '冬天我的皮膚很容易脫皮。', 'Dōngtiān wǒ de pífū hěn róngyì tuōpí.', 'My skin often gets dry and peels in the winter.', 16, 'cc_12', 'Skin'),
  (183, '我的臉圓圓的。', 'Wǒ de liǎn yuányuán de.', 'I have a round face.', 1, 'cc_13', 'Face'),
  (184, '我的臉很大。', 'Wǒ de liǎn hěn dà.', 'I have a big face.', 2, 'cc_13', 'Face'),
  (185, '我的臉很小。', 'Wǒ de liǎn hěn xiǎo.', 'I have a small face.', 3, 'cc_13', 'Face'),
  (186, '我的臉型像我爸。', 'Wǒ de liǎnxíng xiàng wǒ bà.', 'I have the same face shape as my dad.', 4, 'cc_13', 'Face'),
  (187, '我長了一張娃娃臉。', 'Wǒ zhǎng le yì zhāng wáwáliǎn.', 'I have a baby face.', 5, 'cc_13', 'Face'),
  (188, '我的五官長得不錯。', 'Wǒ de wǔguān zhǎng de búcuò.', 'I have attractive facial features.', 6, 'cc_13', 'Face'),
  (189, '我的長相很普通。', 'Wǒ de zhǎngxiàng hěn pǔtōng.', 'I''m average-looking.', 7, 'cc_13', 'Face'),
  (190, '我的額頭很高。', 'Wǒ de étóu hěn gāo.', 'I have a high forehead.', 8, 'cc_13', 'Face'),
  (191, '我的臉頰肉肉的。', 'Wǒ de liǎnjiá ròuròu de.', 'My cheeks are chubby.', 9, 'cc_13', 'Face'),
  (192, '我有雙下巴。', 'Wǒ yǒu shuāng xiàbā.', 'I have a double chin.', 10, 'cc_13', 'Face'),
  (193, '我的下巴尖尖的。', 'Wǒ de xiàba jiānjiān de.', 'I have a pointed chin.', 11, 'cc_13', 'Face'),
  (194, '我想當個小臉美女。', 'Wǒ xiǎng dāng ge xiǎoliǎn měinǚ.', 'I want to have a small, attractive face.', 12, 'cc_13', 'Face'),
  (195, '大家都說我的圓臉很有親和力。', 'Dàjiā dōu shuō wǒ de yuánliǎn hěn yǒu qīnhélì.', 'Everyone says my round face makes me look approachable.', 13, 'cc_13', 'Face'),
  (196, '我總是笑咪咪的。', 'Wǒ zǒngshì xiàomīmī de.', 'I''m always smiling.', 14, 'cc_13', 'Face'),
  (197, '我看起來有點兇。', 'Wǒ kàn qǐlái yǒudiǎn xiōng.', 'I look a little intimidating.', 15, 'cc_13', 'Face'),
  (198, '我平常沒什麼表情。', 'Wǒ píngcháng méi shénme biǎoqíng.', 'I usually don''t show much expression.', 16, 'cc_13', 'Face'),
  (199, '我的顴骨很明顯。', 'Wǒ de quángǔ hěn míngxiǎn.', 'I have prominent cheekbones.', 17, 'cc_13', 'Face'),
  (200, '我的五官很立體。', 'Wǒ de wǔguān hěn lìtǐ.', 'I have well-defined facial features.', 1, 'cc_14', 'Facial Features'),
  (201, '我的眼睛像我媽。', 'Wǒ de yǎnjing xiàng wǒ mā.', 'My eyes look like my mom''s.', 2, 'cc_14', 'Facial Features'),
  (202, '我的眼皮有點腫。', 'Wǒ de yǎnpí yǒudiǎn zhǒng.', 'My eyelids are a little puffy.', 3, 'cc_14', 'Facial Features'),
  (203, '我的眼睛很小。', 'Wǒ de yǎnjing hěn xiǎo.', 'I have small eyes.', 4, 'cc_14', 'Facial Features'),
  (204, '大家都說我的眼睛很大。', 'Dàjiā dōu shuō wǒ de yǎnjing hěn dà.', 'Everyone says I have big eyes.', 5, 'cc_14', 'Facial Features'),
  (205, '我的眼睛細細長長的。', 'Wǒ de yǎnjing xìxì chángcháng de.', 'I have long, narrow eyes.', 6, 'cc_14', 'Facial Features'),
  (206, '我是單眼皮。', 'Wǒ shì dān yǎnpí.', 'I have single eyelids.', 7, 'cc_14', 'Facial Features'),
  (207, '我的睫毛很長。', 'Wǒ de jiémáo hěn cháng.', 'I have long eyelashes.', 8, 'cc_14', 'Facial Features'),
  (208, '我的鼻子很挺。', 'Wǒ de bízi hěn tǐng.', 'I have a high nose bridge.', 9, 'cc_14', 'Facial Features'),
  (209, '我的眼珠是黑色的。', 'Wǒ de yǎnzhū shì hēisè de.', 'My eyes are black.', 10, 'cc_14', 'Facial Features'),
  (210, '我的眉毛很濃。', 'Wǒ de méimao hěn nóng.', 'I have thick eyebrows.', 11, 'cc_14', 'Facial Features'),
  (211, '我有近視。', 'Wǒ yǒu jìnshì.', 'I''m nearsighted.', 12, 'cc_14', 'Facial Features'),
  (212, '我常常修眉毛。', 'Wǒ chángcháng xiū méimao.', 'I trim my eyebrows regularly.', 13, 'cc_14', 'Facial Features'),
  (213, '我的嘴唇很厚。', 'Wǒ de zuǐchún hěn hòu.', 'I have full lips.', 14, 'cc_14', 'Facial Features'),
  (214, '我的嘴巴很大。', 'Wǒ de zuǐba hěn dà.', 'I have a large mouth.', 15, 'cc_14', 'Facial Features'),
  (215, '我留長頭髮。', 'Wǒ liú cháng tóufa.', 'I have long hair.', 1, 'cc_15', 'Hair'),
  (216, '我有瀏海。', 'Wǒ yǒu liúhǎi.', 'I have bangs.', 2, 'cc_15', 'Hair'),
  (217, '我的頭髮是旁分的。', 'Wǒ de tóufa shì pángfēn de.', 'My hair is parted to one side.', 3, 'cc_15', 'Hair'),
  (218, '我的頭髮長到腰。', 'Wǒ de tóufa cháng dào yāo.', 'My hair is waist-length.', 4, 'cc_15', 'Hair'),
  (219, '我的頭髮有自然捲。', 'Wǒ de tóufa yǒu zìrán juǎn.', 'My hair is naturally curly.', 5, 'cc_15', 'Hair'),
  (220, '我的頭髮是中分的。', 'Wǒ de tóufa shì zhōngfēn de.', 'My hair is parted in the middle.', 6, 'cc_15', 'Hair'),
  (221, '我把頭髮燙直了。', 'Wǒ bǎ tóufa tàng zhí le.', 'I had my hair straightened.', 7, 'cc_15', 'Hair'),
  (222, '我染頭髮了。', 'Wǒ rǎn tóufa le.', 'I dyed my hair.', 8, 'cc_15', 'Hair'),
  (223, '我的髮質很好。', 'Wǒ de fàzhí hěn hǎo.', 'I have healthy hair.', 9, 'cc_15', 'Hair'),
  (224, '我把頭髮染成紅色。', 'Wǒ bǎ tóufa rǎn chéng hóngsè.', 'I dyed my hair red.', 10, 'cc_15', 'Hair'),
  (225, '我每天都洗頭。', 'Wǒ měitiān dōu xǐ tóu.', 'I wash my hair every day.', 11, 'cc_15', 'Hair'),
  (226, '我每個星期都會去一次美髮店。', 'Wǒ měi ge xīngqí dōu huì qù yí cì měifǎdiàn.', 'I go to the hair salon once a week.', 12, 'cc_15', 'Hair'),
  (227, '我的頭髮又粗又硬。', 'Wǒ de tóufa yòu cū yòu yìng.', 'My hair is thick and coarse.', 13, 'cc_15', 'Hair'),
  (228, '我平常都綁馬尾。', 'Wǒ píngcháng dōu bǎng mǎwěi.', 'I usually wear my hair in a ponytail.', 14, 'cc_15', 'Hair'),
  (229, '我常常換髮型。', 'Wǒ chángcháng huàn fàxíng.', 'I change my hairstyle often.', 15, 'cc_15', 'Hair'),
  (230, '我很喜歡我的新髮型。', 'Wǒ hěn xǐhuān wǒ de xīn fàxíng.', 'I really like my new hairstyle.', 16, 'cc_15', 'Hair'),
  (231, '我不太會化妝。', 'Wǒ bú tài huì huàzhuāng.', 'I''m not very good at doing makeup.', 1, 'cc_16', 'Appearance & Accessories'),
  (232, '氣色不好的時候我會化妝。', 'Qìsè bù hǎo de shíhou wǒ huì huàzhuāng.', 'I put on makeup when I don''t look well-rested.', 2, 'cc_16', 'Appearance & Accessories'),
  (233, '我想學怎麼化妝。', 'Wǒ xiǎng xué zěnme huàzhuāng.', 'I want to learn how to do makeup.', 3, 'cc_16', 'Appearance & Accessories'),
  (234, '我上大學後才開始化妝。', 'Wǒ shàng dàxué hòu cái kāishǐ huàzhuāng.', 'I didn''t start wearing makeup until college.', 4, 'cc_16', 'Appearance & Accessories'),
  (235, '我平常都會擦睫毛膏。', 'Wǒ píngcháng dōu huì cā jiémáogāo.', 'I usually wear mascara.', 5, 'cc_16', 'Appearance & Accessories'),
  (236, '大家都說我化妝前後差很多。', 'Dàjiā dōu shuō wǒ huàzhuāng qiánhòu chà hěn duō.', 'Everyone says I look very different with makeup on.', 6, 'cc_16', 'Appearance & Accessories'),
  (237, '我從來不戴飾品。', 'Wǒ cónglái bù dài shìpǐn.', 'I never wear jewelry.', 7, 'cc_16', 'Appearance & Accessories'),
  (238, '我只戴結婚戒指。', 'Wǒ zhǐ dài jiéhūn jièzhi.', 'I only wear my wedding ring.', 8, 'cc_16', 'Appearance & Accessories'),
  (239, '這條項鍊對我很有意義，所以我每天都戴。', 'Zhè tiáo xiàngliàn duì wǒ hěn yǒu yìyì, suǒyǐ wǒ měitiān dōu dài.', 'This necklace means a lot to me, so I wear it every day.', 9, 'cc_16', 'Appearance & Accessories'),
  (240, '我很喜歡戴耳環。', 'Wǒ hěn xǐhuān dài ěrhuán.', 'I like wearing earrings.', 10, 'cc_16', 'Appearance & Accessories'),
  (241, '我戴眼鏡。', 'Wǒ dài yǎnjìng.', 'I wear glasses.', 11, 'cc_16', 'Appearance & Accessories'),
  (242, '我們公司規定上班一定要化妝。', 'Wǒmen gōngsī guīdìng shàngbān yídìng yào huàzhuāng.', 'My company requires employees to wear makeup at work.', 12, 'cc_16', 'Appearance & Accessories'),
  (243, '我不喜歡戴眼鏡。', 'Wǒ bù xǐhuān dài yǎnjìng.', 'I don''t like wearing glasses.', 13, 'cc_16', 'Appearance & Accessories'),
  (244, '我都看場合穿衣服。', 'Wǒ dōu kàn chǎnghé chuān yīfu.', 'I dress according to the occasion.', 1, 'cc_17', 'Clothing'),
  (245, '我上班都穿西裝。', 'Wǒ shàngbān dōu chuān xīzhuāng.', 'I wear a suit to work.', 2, 'cc_17', 'Clothing'),
  (246, '放假的時候我都穿得很休閒。', 'Fàngjià de shíhou wǒ dōu chuān de hěn xiūxián.', 'I dress casually on my days off.', 3, 'cc_17', 'Clothing'),
  (247, '我們公司可以穿便服上班。', 'Wǒmen gōngsī kěyǐ chuān biànfú shàngbān.', 'Our company allows casual dress at work.', 4, 'cc_17', 'Clothing'),
  (248, '我上班都穿制服。', 'Wǒ shàngbān dōu chuān zhìfú.', 'I wear a uniform to work.', 5, 'cc_17', 'Clothing'),
  (249, '參加宴會時我會穿小禮服。', 'Cānjiā yànhuì shí wǒ huì chuān xiǎo lǐfú.', 'I wear semi-formal attire when attending banquets.', 6, 'cc_17', 'Clothing'),
  (250, '我喜歡簡單大方的穿搭。', 'Wǒ xǐhuān jiǎndān dàfāng de chuāndā.', 'I like simple and stylish outfits.', 7, 'cc_17', 'Clothing'),
  (251, '我最愛穿T恤跟牛仔褲。', 'Wǒ zuì ài chuān T-xù gēn niúzǎikù.', 'I love wearing T-shirts and jeans.', 8, 'cc_17', 'Clothing'),
  (252, '我比較喜歡長裙。', 'Wǒ bǐjiào xǐhuān chángqún.', 'I prefer long skirts.', 9, 'cc_17', 'Clothing'),
  (253, '我有很多不同款式的牛仔褲。', 'Wǒ yǒu hěn duō bùtóng kuǎnshì de niúzǎikù.', 'I have many different styles of jeans.', 10, 'cc_17', 'Clothing'),
  (254, '我喜歡穿寬鬆一點的衣服。', 'Wǒ xǐhuān chuān kuānsōng yìdiǎn de yīfu.', 'I like wearing loose-fitting clothes.', 11, 'cc_17', 'Clothing'),
  (255, '我常常煩惱今天要穿什麼。', 'Wǒ chángcháng fánnǎo jīntiān yào chuān shénme.', 'I often struggle to decide what to wear.', 12, 'cc_17', 'Clothing'),
  (256, '我每個月大概花五千塊買衣服。', 'Wǒ měi ge yuè dàgài huā wǔqiān kuài mǎi yīfu.', 'I spend about NT$5,000 on clothes each month.', 13, 'cc_17', 'Clothing'),
  (257, '我喜歡穿高跟鞋。', 'Wǒ xǐhuān chuān gāogēnxié.', 'I like wearing high heels.', 14, 'cc_17', 'Clothing'),
  (258, '我還在念書。', 'Wǒ hái zài niànshū.', 'I''m still in school.', 1, 'cc_18', 'Work'),
  (259, '我是朝九晚五的上班族。', 'Wǒ shì zhāo jiǔ wǎn wǔ de shàngbānzú.', 'I work a typical 9-to-5 job.', 2, 'cc_18', 'Work'),
  (260, '我跟朋友一起開店。', 'Wǒ gēn péngyǒu yìqǐ kāi diàn.', 'My friend and I run a shop together.', 3, 'cc_18', 'Work'),
  (261, '我自己創業。', 'Wǒ zìjǐ chuàngyè.', 'I run my own business.', 4, 'cc_18', 'Work'),
  (262, '我的工作跟以前念的完全沒關係。', 'Wǒ de gōngzuò gēn yǐqián niàn de wánquán méi guānxi.', 'My job has nothing to do with what I studied.', 5, 'cc_18', 'Work'),
  (263, '我在家工作。', 'Wǒ zài jiā gōngzuò.', 'I work from home.', 6, 'cc_18', 'Work'),
  (264, '我在電視台上班。', 'Wǒ zài diànshìtái shàngbān.', 'I work at a TV station.', 7, 'cc_18', 'Work'),
  (265, '我在服務業工作。', 'Wǒ zài fúwùyè gōngzuò.', 'I work in the service industry.', 8, 'cc_18', 'Work'),
  (266, '我是公務員。', 'Wǒ shì gōngwùyuán.', 'I''m a civil servant.', 9, 'cc_18', 'Work'),
  (267, '我們公司在台北市中心。', 'Wǒmen gōngsī zài Táiběi shì zhōngxīn.', 'Our company is located in downtown Taipei.', 10, 'cc_18', 'Work'),
  (268, '我做過很多不同的工作。', 'Wǒ zuò guò hěn duō bùtóng de gōngzuò.', 'I''ve worked a lot of different jobs.', 11, 'cc_18', 'Work'),
  (269, '我的工作現在很熱門。', 'Wǒ de gōngzuò xiànzài hěn rèmén.', 'My profession is very popular right now.', 12, 'cc_18', 'Work'),
  (270, '我同時做好幾份工作。', 'Wǒ tóngshí zuò hǎo jǐ fèn gōngzuò.', 'I work multiple jobs at the same time.', 13, 'cc_18', 'Work'),
  (271, '我的工作每天都差不多。', 'Wǒ de gōngzuò měitiān dōu chàbuduō.', 'My work is pretty much the same every day.', 1, 'cc_19', 'Job Responsibilities'),
  (272, '我的工作很複雜。', 'Wǒ de gōngzuò hěn fùzá.', 'My job is very complicated.', 2, 'cc_19', 'Job Responsibilities'),
  (273, '我常常要出差。', 'Wǒ chángcháng yào chūchāi.', 'I have to travel for work quite often.', 3, 'cc_19', 'Job Responsibilities'),
  (274, '我負責產品品管。', 'Wǒ fùzé chǎnpǐn pǐnguǎn.', 'I''m responsible for product quality control.', 4, 'cc_19', 'Job Responsibilities'),
  (275, '我的工作是協助主管。', 'Wǒ de gōngzuò shì xiézhù zhǔguǎn.', 'My job is to assist my manager.', 5, 'cc_19', 'Job Responsibilities'),
  (276, '我的工作常常要長時間盯著電腦。', 'Wǒ de gōngzuò chángcháng yào cháng shíjiān dīngzhe diànnǎo.', 'My job requires me to stare at a computer for long periods of time.', 6, 'cc_19', 'Job Responsibilities'),
  (277, '我需要向客戶介紹產品。', 'Wǒ xūyào xiàng kèhù jièshào chǎnpǐn.', 'I need to introduce products to clients.', 7, 'cc_19', 'Job Responsibilities'),
  (278, '我負責處理客戶的各種問題。', 'Wǒ fùzé chǔlǐ kèhù de gèzhǒng wèntí.', 'I''m responsible for handling customer issues.', 8, 'cc_19', 'Job Responsibilities'),
  (279, '我是從基層一路做上來的。', 'Wǒ shì cóng jīcéng yílù zuò shànglái de.', 'I worked my way up from an entry-level position.', 9, 'cc_19', 'Job Responsibilities'),
  (280, '接電話也是我的工作之一。', 'Jiē diànhuà yě shì wǒ de gōngzuò zhī yī.', 'Answering phone calls is one of my responsibilities.', 10, 'cc_19', 'Job Responsibilities'),
  (281, '我常常一整天都在開會。', 'Wǒ chángcháng yì zhěng tiān dōu zài kāihuì.', 'I''m often in meetings all day.', 11, 'cc_19', 'Job Responsibilities'),
  (282, '我負責行銷企劃。', 'Wǒ fùzé xíngxiāo qǐhuà.', 'I''m responsible for marketing planning.', 12, 'cc_19', 'Job Responsibilities'),
  (283, '我每天九點上班，六點下班。', 'Wǒ měitiān jiǔ diǎn shàngbān, liù diǎn xiàbān.', 'I start work at 9 a.m. and finish at 6 p.m.', 1, 'cc_20', 'Work Schedule'),
  (284, '我每天工作八個小時。', 'Wǒ měitiān gōngzuò bā ge xiǎoshí.', 'I work eight hours a day.', 2, 'cc_20', 'Work Schedule'),
  (285, '我們公司午休一個小時。', 'Wǒmen gōngsī wǔxiū yí ge xiǎoshí.', 'Our company has a one-hour lunch break.', 3, 'cc_20', 'Work Schedule'),
  (286, '我們公司午休時間是十二點到一點。', 'Wǒmen gōngsī wǔxiū shíjiān shì shí''èr diǎn dào yì diǎn.', 'Our lunch break is from 12:00 to 1:00.', 4, 'cc_20', 'Work Schedule'),
  (287, '我的上班時間不固定。', 'Wǒ de shàngbān shíjiān bù gùdìng.', 'My work schedule isn''t fixed.', 5, 'cc_20', 'Work Schedule'),
  (288, '我們公司是輪班制。', 'Wǒmen gōngsī shì lúnbānzhì.', 'Our company uses a shift system.', 6, 'cc_20', 'Work Schedule'),
  (289, '我已經好幾個月沒休假了。', 'Wǒ yǐjīng hǎo jǐ ge yuè méi xiūjià le.', 'I haven''t taken a vacation in several months.', 7, 'cc_20', 'Work Schedule'),
  (290, '我們公司週休二日。', 'Wǒmen gōngsī zhōuxiū èr rì.', 'We have a two-day weekend.', 8, 'cc_20', 'Work Schedule'),
  (291, '我從來沒遲到早退過。', 'Wǒ cónglái méi chídào zǎotuì guò.', 'I''ve never been late or left work early.', 9, 'cc_20', 'Work Schedule'),
  (292, '我一年有七天年假。', 'Wǒ yì nián yǒu qī tiān niánjià.', 'I get seven days of annual leave each year.', 10, 'cc_20', 'Work Schedule'),
  (293, '我常常假日還要加班。', 'Wǒ chángcháng jiàrì hái yào jiābān.', 'I often have to work overtime on weekends and holidays.', 11, 'cc_20', 'Work Schedule'),
  (294, '我常常加班到很晚。', 'Wǒ chángcháng jiābān dào hěn wǎn.', 'I often work late into the night.', 12, 'cc_20', 'Work Schedule'),
  (295, '我在這家公司工作五年了。', 'Wǒ zài zhè jiā gōngsī gōngzuò wǔ nián le.', 'I''ve been working at this company for five years.', 13, 'cc_20', 'Work Schedule'),
  (296, '我很喜歡我的工作。', 'Wǒ hěn xǐhuān wǒ de gōngzuò.', 'I really like my job.', 1, 'cc_21', 'Thoughts About Work'),
  (297, '我是個工作狂。', 'Wǒ shì ge gōngzuòkuáng.', 'I''m a workaholic.', 2, 'cc_21', 'Thoughts About Work'),
  (298, '工作讓我壓力很大。', 'Gōngzuò ràng wǒ yālì hěn dà.', 'My job puts a lot of pressure on me.', 3, 'cc_21', 'Thoughts About Work'),
  (299, '這份工作對我來說很簡單。', 'Zhè fèn gōngzuò duì wǒ lái shuō hěn jiǎndān.', 'This job is easy for me.', 4, 'cc_21', 'Thoughts About Work'),
  (300, '我對自己的工作很有成就感。', 'Wǒ duì zìjǐ de gōngzuò hěn yǒu chéngjiùgǎn.', 'I''m proud of the work I do.', 5, 'cc_21', 'Thoughts About Work'),
  (301, '我覺得這份工作很有挑戰性。', 'Wǒ juéde zhè fèn gōngzuò hěn yǒu tiǎozhànxìng.', 'I think this job is very challenging.', 6, 'cc_21', 'Thoughts About Work'),
  (302, '這份工作讓我能發揮自己的專長。', 'Zhè fèn gōngzuò ràng wǒ néng fāhuī zìjǐ de zhuāncháng.', 'This job lets me use my strengths.', 7, 'cc_21', 'Thoughts About Work'),
  (303, '我從工作中獲得很多成就感。', 'Wǒ cóng gōngzuò zhōng huòdé hěn duō chéngjiùgǎn.', 'I get a lot of satisfaction from my work.', 8, 'cc_21', 'Thoughts About Work'),
  (304, '我覺得自己不太適合這份工作。', 'Wǒ juéde zìjǐ bú tài shìhé zhè fèn gōngzuò.', 'I don''t think this job is a good fit for me.', 9, 'cc_21', 'Thoughts About Work'),
  (305, '我每天都有做不完的工作。', 'Wǒ měitiān dōu yǒu zuò bù wán de gōngzuò.', 'I always have too much work to do.', 10, 'cc_21', 'Thoughts About Work'),
  (306, '我從工作中學到很多東西。', 'Wǒ cóng gōngzuò zhōng xuédào hěn duō dōngxi.', 'I''ve learned a lot from my job.', 11, 'cc_21', 'Thoughts About Work'),
  (307, '我一直在想辦法提高工作效率。', 'Wǒ yìzhí zài xiǎng bànfǎ tígāo gōngzuò xiàolǜ.', 'I''ve been trying to improve my work efficiency.', 12, 'cc_21', 'Thoughts About Work'),
  (308, '我對工作失去熱情了。', 'Wǒ duì gōngzuò shīqù rèqíng le.', 'I''ve lost my enthusiasm for work.', 13, 'cc_21', 'Thoughts About Work'),
  (309, '工作讓我認識了很多朋友。', 'Gōngzuò ràng wǒ rènshi le hěn duō péngyǒu.', 'Work has helped me make a lot of friends.', 14, 'cc_21', 'Thoughts About Work'),
  (310, '我每天都很享受工作。', 'Wǒ měitiān dōu hěn xiǎngshòu gōngzuò.', 'I enjoy my work every day.', 1, 'cc_22', 'Work Attitude'),
  (311, '我全心投入工作。', 'Wǒ quánxīn tóurù gōngzuò.', 'I devote myself fully to my work.', 2, 'cc_22', 'Work Attitude'),
  (312, '我都會準時完成工作。', 'Wǒ dōu huì zhǔnshí wánchéng gōngzuò.', 'I always finish my work on time.', 3, 'cc_22', 'Work Attitude'),
  (313, '我從不遲到早退。', 'Wǒ cóng bù chídào zǎotuì.', 'I never arrive late or leave early.', 4, 'cc_22', 'Work Attitude'),
  (314, '上班時間我不處理私事。', 'Shàngbān shíjiān wǒ bù chǔlǐ sīshì.', 'I don''t take care of personal matters during work hours.', 5, 'cc_22', 'Work Attitude'),
  (315, '公司交代的工作我都會盡力完成。', 'Gōngsī jiāodài de gōngzuò wǒ dōu huì jìnlì wánchéng.', 'I always do my best to complete the tasks assigned to me.', 6, 'cc_22', 'Work Attitude'),
  (316, '我會盡力滿足客戶的需求。', 'Wǒ huì jìnlì mǎnzú kèhù de xūqiú.', 'I always do my best to meet customers'' needs.', 7, 'cc_22', 'Work Attitude'),
  (317, '我做事很小心，不想出錯。', 'Wǒ zuòshì hěn xiǎoxīn, bù xiǎng chūcuò.', 'I work carefully because I don''t want to make mistakes.', 8, 'cc_22', 'Work Attitude'),
  (318, '我不會隨便請假。', 'Wǒ bù huì suíbiàn qǐngjià.', 'I don''t take time off without a good reason.', 9, 'cc_22', 'Work Attitude'),
  (319, '我希望能從工作中學習和成長。', 'Wǒ xīwàng néng cóng gōngzuò zhōng xuéxí hé chéngzhǎng.', 'I hope to learn and grow through my work.', 10, 'cc_22', 'Work Attitude'),
  (320, '我不喜歡把今天的事拖到明天。', 'Wǒ bù xǐhuān bǎ jīntiān de shì tuō dào míngtiān.', 'I don''t like putting today''s work off until tomorrow.', 11, 'cc_22', 'Work Attitude'),
  (321, '我不讓自己的情緒影響工作。', 'Wǒ bù ràng zìjǐ de qíngxù yǐngxiǎng gōngzuò.', 'I don''t let my emotions affect my work.', 12, 'cc_22', 'Work Attitude'),
  (322, '我失業了。', 'Wǒ shīyè le.', 'I lost my job.', 1, 'cc_23', 'Job Changes'),
  (323, '我加薪了。', 'Wǒ jiāxīn le.', 'I got a raise.', 2, 'cc_23', 'Job Changes'),
  (324, '我們公司最近裁了很多人。', 'Wǒmen gōngsī zuìjìn cái le hěn duō rén.', 'Our company recently laid off a lot of employees.', 3, 'cc_23', 'Job Changes'),
  (325, '我被減薪了。', 'Wǒ bèi jiǎnxīn le.', 'My salary was reduced.', 4, 'cc_23', 'Job Changes'),
  (326, '我升職了。', 'Wǒ shēngzhí le.', 'I got promoted.', 5, 'cc_23', 'Job Changes'),
  (327, '我被降職了。', 'Wǒ bèi jiàngzhí le.', 'I got demoted.', 6, 'cc_23', 'Job Changes'),
  (328, '我換工作了。', 'Wǒ huàn gōngzuò le.', 'I changed jobs.', 7, 'cc_23', 'Job Changes'),
  (329, '我要被派到國外工作。', 'Wǒ yào bèi pài dào guówài gōngzuò.', 'I''m going to be assigned to work overseas.', 8, 'cc_23', 'Job Changes'),
  (330, '我要調到總公司。', 'Wǒ yào diào dào zǒng gōngsī.', 'I''m being transferred to headquarters.', 9, 'cc_23', 'Job Changes'),
  (331, '我被調到別的部門了。', 'Wǒ bèi diào dào bié de bùmén le.', 'I was transferred to another department.', 10, 'cc_23', 'Job Changes'),
  (332, '我剛通過試用期。', 'Wǒ gāng tōngguò shìyòngqī.', 'I just passed my probation period.', 11, 'cc_23', 'Job Changes'),
  (333, '公司要再請兩個助理。', 'Gōngsī yào zài qǐng liǎng ge zhùlǐ.', 'The company is hiring two more assistants.', 12, 'cc_23', 'Job Changes'),
  (334, '我們部門來了一位新同事。', 'Wǒmen bùmén lái le yí wèi xīn tóngshì.', 'A new coworker joined our department.', 13, 'cc_23', 'Job Changes'),
  (335, '我有新主管了。', 'Wǒ yǒu xīn zhǔguǎn le.', 'I have a new manager.', 14, 'cc_23', 'Job Changes'),
  (336, '我明年要退休了。', 'Wǒ míngnián yào tuìxiū le.', 'I''m retiring next year.', 15, 'cc_23', 'Job Changes'),
  (337, '我被裁員了。', 'Wǒ bèi cáiyuán le.', 'I got laid off.', 16, 'cc_23', 'Job Changes'),
  (338, '我想找一份朝九晚五的工作。', 'Wǒ xiǎng zhǎo yí fèn zhāo jiǔ wǎn wǔ de gōngzuò.', 'I want a regular 9-to-5 job.', 1, 'cc_24', 'Career Goals Pt. 1'),
  (339, '我想在時尚產業工作。', 'Wǒ xiǎng zài shíshàng chǎnyè gōngzuò.', 'I want to work in the fashion industry.', 2, 'cc_24', 'Career Goals Pt. 1'),
  (340, '我想做自己有興趣的工作。', 'Wǒ xiǎng zuò zìjǐ yǒu xìngqù de gōngzuò.', 'I want a job that I''m interested in.', 3, 'cc_24', 'Career Goals Pt. 1'),
  (341, '進演藝圈一直是我的夢想。', 'Jìn yǎnyìquān yìzhí shì wǒ de mèngxiǎng.', 'Working in the entertainment industry has always been my dream.', 4, 'cc_24', 'Career Goals Pt. 1'),
  (342, '我想當公務員。', 'Wǒ xiǎng dāng gōngwùyuán.', 'I want to become a civil servant.', 5, 'cc_24', 'Career Goals Pt. 1'),
  (343, '我希望自己創業。', 'Wǒ xīwàng zìjǐ chuàngyè.', 'I hope to start my own business.', 6, 'cc_24', 'Career Goals Pt. 1'),
  (344, '我希望工作跟所學有關。', 'Wǒ xīwàng gōngzuò gēn suǒxué yǒuguān.', 'I hope my job is related to what I studied.', 7, 'cc_24', 'Career Goals Pt. 1'),
  (345, '我想開一間店。', 'Wǒ xiǎng kāi yì jiān diàn.', 'I want to open a shop.', 8, 'cc_24', 'Career Goals Pt. 1'),
  (346, '我想當自由接案的SOHO族。', 'Wǒ xiǎng dāng zìyóu jiē''àn de SOHO zú.', 'I want to be a freelancer and work from home.', 9, 'cc_24', 'Career Goals Pt. 1'),
  (347, '我一直很想去外商公司上班。', 'Wǒ yìzhí hěn xiǎng qù wàishāng gōngsī shàngbān.', 'I''ve always wanted to work for a foreign company.', 10, 'cc_24_1', 'Career Goals Pt. 2'),
  (348, '我想去國外工作。', 'Wǒ xiǎng qù guówài gōngzuò.', 'I want to work abroad.', 11, 'cc_24_1', 'Career Goals Pt. 2'),
  (349, '我希望能在大城市工作。', 'Wǒ xīwàng néng zài dà chéngshì gōngzuò.', 'I hope to work in a big city.', 12, 'cc_24_1', 'Career Goals Pt. 2'),
  (350, '我希望從政。', 'Wǒ xīwàng cóngzhèng.', 'I hope to work in politics.', 13, 'cc_24_1', 'Career Goals Pt. 2'),
  (351, '我想從事跟媒體有關的工作。', 'Wǒ xiǎng cóngshì gēn méitǐ yǒuguān de gōngzuò.', 'I want a job related to the media industry.', 14, 'cc_24_1', 'Career Goals Pt. 2'),
  (352, '我想進3C產業工作。', 'Wǒ xiǎng jìn sān C chǎnyè gōngzuò.', 'I want to work in the tech/electronics industry.', 15, 'cc_24_1', 'Career Goals Pt. 2'),
  (353, '我想做服務業。', 'Wǒ xiǎng zuò fúwùyè.', 'I want to work in the service industry.', 16, 'cc_24_1', 'Career Goals Pt. 2'),
  (354, '我想找一份需要常跟人接觸的工作。', 'Wǒ xiǎng zhǎo yí fèn xūyào cháng gēn rén jiēchù de gōngzuò.', 'I want a job where I interact with people a lot.', 17, 'cc_24_1', 'Career Goals Pt. 2'),
  (355, '我只想在家當家庭主婦。', 'Wǒ zhǐ xiǎng zài jiā dāng jiātíng zhǔfù.', 'I just want to be a homemaker.', 18, 'cc_24_1', 'Career Goals Pt. 2'),
  (356, '我希望公司會辦員工旅遊。', 'Wǒ xīwàng gōngsī huì bàn yuángōng lǚyóu.', 'I wish my company organized employee trips.', 19, 'cc_24_1', 'Career Goals Pt. 2'),
  (357, '我打算換工作。', 'Wǒ dǎsuàn huàn gōngzuò.', 'I plan to change jobs.', 20, 'cc_24_1', 'Career Goals Pt. 2'),
  (358, '我希望公司福利好一點。', 'Wǒ xīwàng gōngsī fúlì hǎo yìdiǎn.', 'I wish my company had better benefits.', 1, 'cc_25', 'Preferred Work Environment'),
  (359, '我希望能進員工超過一百人的大公司。', 'Wǒ xīwàng néng jìn yuángōng chāoguò yì bǎi rén de dà gōngsī.', 'I want to work for a large company with more than 100 employees.', 2, 'cc_25', 'Preferred Work Environment'),
  (360, '我希望錢多事少。', 'Wǒ xīwàng qián duō shì shǎo.', 'I wish I could earn more and work less.', 3, 'cc_25', 'Preferred Work Environment'),
  (361, '我希望能進員工不到二十人的小公司。', 'Wǒ xīwàng néng jìn yuángōng bú dào èrshí rén de xiǎo gōngsī.', 'I want to work for a small company with fewer than 20 employees.', 4, 'cc_25', 'Preferred Work Environment'),
  (362, '我希望公司重視員工培訓。', 'Wǒ xīwàng gōngsī zhòngshì yuángōng péixùn.', 'I hope my company values employee training.', 5, 'cc_25', 'Preferred Work Environment'),
  (363, '我希望公司交通方便。', 'Wǒ xīwàng gōngsī jiāotōng fāngbiàn.', 'I hope my workplace is easy to get to.', 6, 'cc_25', 'Preferred Work Environment'),
  (364, '我希望公司離家近一點。', 'Wǒ xīwàng gōngsī lí jiā jìn yìdiǎn.', 'I wish my workplace were closer to home.', 7, 'cc_25', 'Preferred Work Environment'),
  (365, '我希望公司有完善的升遷制度。', 'Wǒ xīwàng gōngsī yǒu wánshàn de shēngqiān zhìdù.', 'I hope my company has a clear promotion system.', 8, 'cc_25', 'Preferred Work Environment'),
  (366, '我希望可以準時下班。', 'Wǒ xīwàng kěyǐ zhǔnshí xiàbān.', 'I wish I could leave work on time.', 9, 'cc_25', 'Preferred Work Environment'),
  (367, '我希望每年有十天年假。', 'Wǒ xīwàng měinián yǒu shí tiān niánjià.', 'I wish I had ten days of annual leave each year.', 10, 'cc_25', 'Preferred Work Environment'),
  (368, '我希望有豐厚的年終獎金。', 'Wǒ xīwàng yǒu fēnghòu de niánzhōng jiǎngjīn.', 'I hope to get a generous year-end bonus.', 11, 'cc_25', 'Preferred Work Environment'),
  (369, '我希望同事好相處。', 'Wǒ xīwàng tóngshì hǎo xiāngchǔ.', 'I hope my coworkers are easy to get along with.', 12, 'cc_25', 'Preferred Work Environment'),
  (370, '我希望自己變得更漂亮。', 'Wǒ xīwàng zìjǐ biàn de gèng piàoliang.', 'I wish I were more attractive.', 1, 'cc_26', 'Appearance Goals'),
  (371, '我希望自己能成為大家注意的焦點。', 'Wǒ xīwàng zìjǐ néng chéngwéi dàjiā zhùyì de jiǎodiǎn.', 'I wish I could be the center of attention.', 2, 'cc_26', 'Appearance Goals'),
  (372, '我希望我的皮膚完美無瑕。', 'Wǒ xīwàng wǒ de pífū wánměi wúxiá.', 'I wish I had flawless skin.', 3, 'cc_26', 'Appearance Goals'),
  (373, '我希望自己看起來更年輕。', 'Wǒ xīwàng zìjǐ kàn qǐlái gèng niánqīng.', 'I wish I looked younger.', 4, 'cc_26', 'Appearance Goals'),
  (374, '我希望臉上的斑少一點。', 'Wǒ xīwàng liǎn shàng de bān shǎo yìdiǎn.', 'I wish I had fewer freckles.', 5, 'cc_26', 'Appearance Goals'),
  (375, '我希望眼睛再大一點。', 'Wǒ xīwàng yǎnjing zài dà yìdiǎn.', 'I wish I had bigger eyes.', 6, 'cc_26', 'Appearance Goals'),
  (376, '我很羨慕皮膚白的人。', 'Wǒ hěn xiànmù pífū bái de rén.', 'I envy people with fair skin.', 7, 'cc_26', 'Appearance Goals'),
  (377, '我很羨慕臉小的人。', 'Wǒ hěn xiànmù liǎn xiǎo de rén.', 'I envy people with small faces.', 8, 'cc_26', 'Appearance Goals'),
  (378, '我希望自己是雙眼皮。', 'Wǒ xīwàng zìjǐ shì shuāng yǎnpí.', 'I wish I had double eyelids.', 9, 'cc_26', 'Appearance Goals'),
  (379, '我想要又長又翹的睫毛。', 'Wǒ xiǎng yào yòu cháng yòu qiào de jiémáo.', 'I want long, curled eyelashes.', 10, 'cc_26', 'Appearance Goals'),
  (380, '我希望鼻子再挺一點。', 'Wǒ xīwàng bízi zài tǐng yìdiǎn.', 'I wish I had a higher nose bridge.', 11, 'cc_26', 'Appearance Goals'),
  (381, '我想要性感一點的嘴唇。', 'Wǒ xiǎng yào xìnggǎn yìdiǎn de zuǐchún.', 'I want fuller, more attractive lips.', 12, 'cc_26', 'Appearance Goals'),
  (382, '我正在努力減少臉上的細紋。', 'Wǒ zhèngzài nǔlì jiǎnshǎo liǎn shàng de xìwén.', 'I''m trying to reduce the wrinkles on my face.', 13, 'cc_26', 'Appearance Goals'),
  (383, '我希望沒有黑眼圈。', 'Wǒ xīwàng méiyǒu hēiyǎnquān.', 'I wish I didn''t have dark circles under my eyes.', 14, 'cc_26', 'Appearance Goals'),
  (384, '我希望自己看起來更有自信。', 'Wǒ xīwàng zìjǐ kàn qǐlái gèng yǒu zìxìn.', 'I wish I looked more confident.', 15, 'cc_26', 'Appearance Goals'),
  (385, '我希望一直維持好身材。', 'Wǒ xīwàng yìzhí wéichí hǎo shēncái.', 'I hope I can stay in shape forever.', 1, 'cc_27', 'Body Goals'),
  (386, '我希望身材再好一點。', 'Wǒ xīwàng shēncái zài hǎo yìdiǎn.', 'I wish I had a better figure.', 2, 'cc_27', 'Body Goals'),
  (387, '我希望維持現在的體重。', 'Wǒ xīwàng wéichí xiànzài de tǐzhòng.', 'I want to maintain my current weight.', 3, 'cc_27', 'Body Goals'),
  (388, '我想減肥。', 'Wǒ xiǎng jiǎnféi.', 'I want to lose weight.', 4, 'cc_27', 'Body Goals'),
  (389, '我想瘦五公斤。', 'Wǒ xiǎng shòu wǔ gōngjīn.', 'I want to lose five kilograms.', 5, 'cc_27', 'Body Goals'),
  (390, '我想胖三公斤。', 'Wǒ xiǎng pàng sān gōngjīn.', 'I want to gain three kilograms.', 6, 'cc_27', 'Body Goals'),
  (391, '我希望自己再高一點。', 'Wǒ xīwàng zìjǐ zài gāo yìdiǎn.', 'I wish I were a little taller.', 7, 'cc_27', 'Body Goals'),
  (392, '我希望不要再長高了。', 'Wǒ xīwàng búyào zài zhǎnggāo le.', 'I hope I don''t get any taller.', 8, 'cc_27', 'Body Goals'),
  (393, '我希望身上不要有多餘的贅肉。', 'Wǒ xīwàng shēnshang búyào yǒu duōyú de zhuìròu.', 'I wish I didn''t have any excess body fat.', 9, 'cc_27', 'Body Goals'),
  (394, '我希望有一雙美腿。', 'Wǒ xīwàng yǒu yì shuāng měituǐ.', 'I wish I had beautiful legs.', 10, 'cc_27', 'Body Goals'),
  (395, '我希望胸部再豐滿一點。', 'Wǒ xīwàng xiōngbù zài fēngmǎn yìdiǎn.', 'I wish I had a fuller bust.', 11, 'cc_27', 'Body Goals'),
  (396, '我希望能瘦小腹。', 'Wǒ xīwàng néng shòu xiǎofù.', 'I want to get rid of my belly fat.', 12, 'cc_27', 'Body Goals'),
  (397, '我希望雙腿再細一點。', 'Wǒ xīwàng shuāngtuǐ zài xì yìdiǎn.', 'I wish my legs were slimmer.', 13, 'cc_27', 'Body Goals'),
  (398, '我希望手臂更結實一點。', 'Wǒ xīwàng shǒubì gèng jiēshi yìdiǎn.', 'I wish my arms were more toned.', 14, 'cc_27', 'Body Goals'),
  (399, '我想要小蠻腰。', 'Wǒ xiǎng yào xiǎományāo.', 'I want a slim waist.', 15, 'cc_27', 'Body Goals'),
  (400, '我希望屁股小一點、翹一點。', 'Wǒ xīwàng pìgu xiǎo yìdiǎn, qiào yìdiǎn.', 'I wish I had a smaller, more shapely butt.', 16, 'cc_27', 'Body Goals'),
  (401, '我對未來有很多計畫。', 'Wǒ duì wèilái yǒu hěn duō jìhuà.', 'I have a lot of plans for the future.', 1, 'cc_28', 'Life Plans'),
  (402, '我對未來還沒什麼想法。', 'Wǒ duì wèilái hái méi shénme xiǎngfǎ.', 'I don''t really have any plans for the future yet.', 2, 'cc_28', 'Life Plans'),
  (403, '我打算出國留學。', 'Wǒ dǎsuàn chūguó liúxué.', 'I plan to study abroad.', 3, 'cc_28', 'Life Plans'),
  (404, '我想一步一步來。', 'Wǒ xiǎng yí bù yí bù lái.', 'I just want to take things one step at a time.', 4, 'cc_28', 'Life Plans'),
  (405, '我希望能闖出自己的一番事業。', 'Wǒ xīwàng néng chuǎng chū zìjǐ de yì fān shìyè.', 'I hope to build a successful career for myself.', 5, 'cc_28', 'Life Plans'),
  (406, '我打算五年後自己創業。', 'Wǒ dǎsuàn wǔ nián hòu zìjǐ chuàngyè.', 'I plan to start my own business in five years.', 6, 'cc_28', 'Life Plans'),
  (407, '我希望二十七歲以前結婚。', 'Wǒ xīwàng èrshíqī suì yǐqián jiéhūn.', 'I hope to get married before I turn 27.', 7, 'cc_28', 'Life Plans'),
  (408, '我想三十歲以後開一間店。', 'Wǒ xiǎng sānshí suì yǐhòu kāi yì jiān diàn.', 'I want to open a shop after I turn 30.', 8, 'cc_28', 'Life Plans'),
  (409, '我想當頂客族。', 'Wǒ xiǎng dāng dǐngkèzú.', 'I want to be part of a DINK household (Double Income, No Kids).', 9, 'cc_28', 'Life Plans'),
  (410, '我打算六十歲退休。', 'Wǒ dǎsuàn liùshí suì tuìxiū.', 'I plan to retire at 60.', 10, 'cc_28', 'Life Plans'),
  (411, '我希望三十歲以前生小孩。', 'Wǒ xīwàng sānshí suì yǐqián shēng xiǎohái.', 'I hope to have a child before I turn 30.', 11, 'cc_28', 'Life Plans'),
  (412, '我想生兩個小孩。', 'Wǒ xiǎng shēng liǎng ge xiǎohái.', 'I want to have two children.', 12, 'cc_28', 'Life Plans'),
  (413, '我這輩子一定要環遊世界。', 'Wǒ zhè bèizi yídìng yào huányóu shìjiè.', 'I definitely want to travel around the world someday.', 13, 'cc_28', 'Life Plans'),
  (414, '我希望等經濟穩定以後再結婚。', 'Wǒ xīwàng děng jīngjì wěndìng yǐhòu zài jiéhūn.', 'I hope to get married after I''m financially stable.', 14, 'cc_28', 'Life Plans'),
  (415, '我每天都會記帳。', 'Wǒ měitiān dōu huì jìzhàng.', 'I keep track of my expenses every day.', 1, 'cc_29', 'Financial Planning'),
  (416, '我每個月都會存薪水的三分之一。', 'Wǒ měi ge yuè dōu huì cún xīnshuǐ de sān fēn zhī yī.', 'I save one-third of my salary every month.', 2, 'cc_29', 'Financial Planning'),
  (417, '我有投資股票。', 'Wǒ yǒu tóuzī gǔpiào.', 'I invest in stocks.', 3, 'cc_29', 'Financial Planning'),
  (418, '我打算三十歲買房子。', 'Wǒ dǎsuàn sānshí suì mǎi fángzi.', 'I plan to buy a house when I''m 30.', 4, 'cc_29', 'Financial Planning'),
  (419, '我每個月存五千塊。', 'Wǒ měi ge yuè cún wǔqiān kuài.', 'I save NT$5,000 every month.', 5, 'cc_29', 'Financial Planning'),
  (420, '我希望二十五歲前存到第一個一百萬。', 'Wǒ xīwàng èrshíwǔ suì qián cún dào dì yí ge yìbǎi wàn.', 'I hope to save my first million before I turn 25.', 6, 'cc_29', 'Financial Planning'),
  (421, '我有在做期貨。', 'Wǒ yǒu zài zuò qíhuò.', 'I trade futures.', 7, 'cc_29', 'Financial Planning'),
  (422, '我希望十年內把車貸還清。', 'Wǒ xīwàng shí nián nèi bǎ chēdài huán qīng.', 'I hope to pay off my car loan within ten years.', 8, 'cc_29', 'Financial Planning'),
  (423, '我有加入信用合作社。', 'Wǒ yǒu jiārù xìnyòng hézuòshè.', 'I''ve joined a credit cooperative.', 9, 'cc_29', 'Financial Planning'),
  (424, '我不會亂花錢。', 'Wǒ bú huì luàn huā qián.', 'I don''t spend money carelessly.', 10, 'cc_29', 'Financial Planning'),
  (425, '我把錢存在銀行定存。', 'Wǒ bǎ qián cún zài yínháng dìngcún.', 'I keep my money in a fixed-term deposit account.', 11, 'cc_29', 'Financial Planning'),
  (426, '我有幫自己買保險。', 'Wǒ yǒu bāng zìjǐ mǎi bǎoxiǎn.', 'I''ve bought insurance for myself.', 12, 'cc_29', 'Financial Planning'),
  (427, '我完全不懂理財。', 'Wǒ wánquán bù dǒng lǐcái.', 'I don''t know anything about personal finance.', 13, 'cc_29', 'Financial Planning'),
  (428, '我得開始存小孩的教育基金。', 'Wǒ děi kāishǐ cún xiǎohái de jiàoyù jījīn.', 'I need to start saving for my child''s education.', 14, 'cc_29', 'Financial Planning'),
  (429, '我花錢都不太規劃。', 'Wǒ huā qián dōu bú tài guīhuà.', 'I don''t really plan my spending.', 15, 'cc_29', 'Financial Planning'),
  (430, '我貸款創業。', 'Wǒ dàikuǎn chuàngyè.', 'I took out a loan to start my own business.', 16, 'cc_29', 'Financial Planning');

with existing_deck as (
  select id
    from sentence_decks
   where deck_kind = 'System'
     and user_id is null
     and name = '5,000 Chinese Conversation Sentences'
     and source_language = 'English (America)'
     and target_language = 'Mandarin Chinese (TW)'
   order by created_at asc
   limit 1
), inserted_deck as (
  insert into sentence_decks (
    user_id,
    deck_kind,
    name,
    description,
    coins,
    level,
    visibility,
    source_language,
    target_language
  )
  select
    null,
    'System',
    '5,000 Chinese Conversation Sentences',
    'A system deck of Mandarin Chinese conversation sentences imported from CSV.',
    0,
    'A1',
    'Public',
    'English (America)',
    'Mandarin Chinese (TW)'
  where not exists (select 1 from existing_deck)
  returning id
), target_deck as (
  select id from existing_deck
  union all
  select id from inserted_deck
), topic_first_seen as (
  select topic,
         min(csv_position) as first_position
    from chinese_conversation_sentence_payload
   group by topic
), topic_source as (
  select topic,
         row_number() over (order by first_position) as topic_order
    from topic_first_seen
)
insert into sentence_deck_topics (deck_id, name, description, sort_order)
select target_deck.id,
       topic_source.topic,
       '',
       topic_source.topic_order
  from target_deck
 cross join topic_source
 where not exists (
   select 1
     from sentence_deck_topics existing_topic
    where existing_topic.deck_id = target_deck.id
      and existing_topic.name = topic_source.topic
 );

with payload as (
  select *
    from chinese_conversation_sentence_payload
)
insert into sentences (
  source_language,
  target_language,
  target,
  translation,
  romanization,
  level,
  topic,
  difficulty,
  notes,
  source,
  variations
)
select
  'English (America)',
  'Mandarin Chinese (TW)',
  payload.chinese,
  payload.english,
  payload.pinyin,
  'A1',
  payload.topic,
  1,
  case when nullif(payload.type_code, '') is null then '' else 'CSV type: ' || payload.type_code end,
  '5,000 Chinese Conversation Sentences',
  '[]'::jsonb
from payload
where not exists (
  select 1
    from sentences existing_sentence
   where existing_sentence.source = '5,000 Chinese Conversation Sentences'
     and existing_sentence.source_language = 'English (America)'
     and existing_sentence.target_language = 'Mandarin Chinese (TW)'
     and existing_sentence.target = payload.chinese
     and existing_sentence.translation = payload.english
);

with target_deck as (
  select id
    from sentence_decks
   where deck_kind = 'System'
     and user_id is null
     and name = '5,000 Chinese Conversation Sentences'
     and source_language = 'English (America)'
     and target_language = 'Mandarin Chinese (TW)'
   order by created_at asc
   limit 1
), payload as (
  select *
    from chinese_conversation_sentence_payload
), resolved_rows as (
  select target_deck.id as deck_id,
         topic.id as topic_id,
         sentence.id as sentence_id,
         payload.item_order,
         payload.csv_position
    from target_deck
    join payload on true
    join sentence_deck_topics topic
      on topic.deck_id = target_deck.id
     and topic.name = payload.topic
    join sentences sentence
      on sentence.source = '5,000 Chinese Conversation Sentences'
     and sentence.source_language = 'English (America)'
     and sentence.target_language = 'Mandarin Chinese (TW)'
     and sentence.target = payload.chinese
     and sentence.translation = payload.english
)
insert into sentence_deck_items (deck_id, topic_id, sentence_id, sort_order)
select resolved_rows.deck_id,
       resolved_rows.topic_id,
       resolved_rows.sentence_id,
       resolved_rows.item_order
  from resolved_rows
 where not exists (
   select 1
     from sentence_deck_items existing_item
    where existing_item.deck_id = resolved_rows.deck_id
      and existing_item.sentence_id = resolved_rows.sentence_id
 )
 order by resolved_rows.csv_position;

commit;
