truncate table
  direct_messages,
  direct_conversations,
  saved_posts,
  post_comments,
  post_likes,
  posts,
  goal_supports,
  goal_templates,
  goals,
  user_learning_path_progress,
  learning_path_items,
  learning_paths,
  user_story_states,
  story_translations,
  stories,
  story_categories,
  user_sentence_reviews,
  sentences,
  sentence_packs,
  coin_transactions,
  coin_rules,
  user_sessions,
  wallets,
  user_languages,
  users,
  supported_languages
restart identity cascade;
